import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Lora,
  Roboto,
  Montserrat,
  Mulish,
  Inter,
} from 'next/font/google';

import './globals.css';
import Script from 'next/script';
import { Header } from './Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const lora = Lora({
  variable: '--font-lora',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

const mulish = Mulish({
  variable: '--font-mulish',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="theme-init" strategy="afterInteractive">
          {`(function(){ 
                  try {
                var d=document.documentElement;
                var ls=localStorage.getItem('theme');
                if (ls==='dark' || (!ls && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  d.setAttribute('data-theme','dark');
                } else {
                  d.setAttribute('data-theme','light');
                }
              } catch(e) {} })();`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} ${roboto.variable} ${montserrat.variable} ${mulish.variable} ${inter.variable} bg-bgmain antialiased`}
      >
        <Header />
        <div className="mt-14">{children}</div>
      </body>
    </html>
  );
}
